name: 'Bing spellcheck github action'
author: 'Tony Diaz'
description: 'Spell check you comments'
with:
  spellchecker-key:
    required: true
  spellchecker-endpoint:
    required: true 
  spellcheck-confidence: 
    description: 'minimum confidence to correct the spelling'
    required: true  
    default: 0.80 #80%
  github-secret:  
    required: true 
runs:
  using: 'node12'
  main: 'dist/index.js'
