name: 'Bing spellcheck github action'
description: 'Spell check you comments'
with:
  spellchecker-key:
    required: true
  spellchecker-endpoint:
    required: true
  github-secret:  
  # milliseconds:  # id of input
  #   description: 'number of milliseconds to wait'
  #   required: true
  #   default: '1000'
# outputs:
#   time: # output will be available to future steps
    # description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
