name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        spellchecker-key: ${{ secrets.SPELLCHECKER_KEY }}
        spellchecker-endpoint: ${{ secrets.SPELLCHECKER_ENDPOINT }}
        github-secret:  ${{ secrets.GITHUB_TOKEN }}
